export interface Command {
  id: string;
  category: string;
  command: string;
  description: string;
  vendor: string;
  os?: string;
  mode?: string;
}

export const commandsData: Command[] = [
  // ===== CISCO COMMANDS =====
  {
    id: "cisco-1",
    vendor: "Cisco",
    category: "Interface Status",
    command: "show interface status",
    description: "Exibe o status resumido de todas as interfaces (Link e Protocol)",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-2",
    vendor: "Cisco",
    category: "Optical Signals",
    command: "show interface [tipo/número] transceiver detail",
    description: "Exibe os níveis de potência óptica (TX/RX) do transceptor SFP",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-3",
    vendor: "Cisco",
    category: "Configuration",
    command: "configure terminal",
    description: "Entra no modo de configuração global",
    os: "IOS / IOS-XE",
    mode: "User Mode",
  },
  {
    id: "cisco-4",
    vendor: "Cisco",
    category: "Configuration",
    command: "write memory",
    description: "Salva a configuração na memória não volátil",
    os: "IOS / IOS-XE",
    mode: "Privileged Mode",
  },
  {
    id: "cisco-5",
    vendor: "Cisco",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "IOS / IOS-XE",
    mode: "Interface Config",
  },
  {
    id: "cisco-6",
    vendor: "Cisco",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a interface",
    os: "IOS / IOS-XE",
    mode: "Interface Config",
  },
  {
    id: "cisco-7",
    vendor: "Cisco",
    category: "Diagnostics",
    command: "ping [IP]",
    description: "Testa conectividade com um endereço IP",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-8",
    vendor: "Cisco",
    category: "Diagnostics",
    command: "traceroute [IP]",
    description: "Exibe o caminho percorrido pelos pacotes até o destino",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-9",
    vendor: "Cisco",
    category: "Logs",
    command: "show logging",
    description: "Exibe os logs do sistema",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-10",
    vendor: "Cisco",
    category: "Configuration",
    command: "show running-config",
    description: "Exibe a configuração atual em execução",
    os: "IOS / IOS-XE",
  },

  // ===== HUAWEI VRP COMMANDS =====
  {
    id: "huawei-1",
    vendor: "Huawei",
    category: "Interface Status",
    command: "display interface brief",
    description: "Exibe o status resumido de todas as interfaces (Link e Protocol)",
    os: "VRP",
  },
  {
    id: "huawei-2",
    vendor: "Huawei",
    category: "Optical Signals",
    command: "display interface [tipo/número] transceiver verbose",
    description: "Exibe os níveis de potência óptica (TX/RX) e temperatura do transceptor",
    os: "VRP",
  },
  {
    id: "huawei-3",
    vendor: "Huawei",
    category: "Configuration",
    command: "system-view",
    description: "Entra no modo de configuração global",
    os: "VRP",
    mode: "User View",
  },
  {
    id: "huawei-4",
    vendor: "Huawei",
    category: "Configuration",
    command: "save",
    description: "Salva a configuração na memória não volátil",
    os: "VRP",
    mode: "System View",
  },
  {
    id: "huawei-5",
    vendor: "Huawei",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "VRP",
    mode: "Interface View",
  },
  {
    id: "huawei-6",
    vendor: "Huawei",
    category: "Shutdown",
    command: "undo shutdown",
    description: "Ativa a interface",
    os: "VRP",
    mode: "Interface View",
  },
  {
    id: "huawei-7",
    vendor: "Huawei",
    category: "Diagnostics",
    command: "ping [IP]",
    description: "Testa conectividade com um endereço IP",
    os: "VRP",
  },
  {
    id: "huawei-8",
    vendor: "Huawei",
    category: "Diagnostics",
    command: "tracert [IP]",
    description: "Exibe o caminho percorrido pelos pacotes até o destino",
    os: "VRP",
  },
  {
    id: "huawei-9",
    vendor: "Huawei",
    category: "Logs",
    command: "display logbuffer",
    description: "Exibe os logs de eventos do sistema",
    os: "VRP",
  },
  {
    id: "huawei-10",
    vendor: "Huawei",
    category: "Configuration",
    command: "display current-configuration",
    description: "Exibe a configuração atual em execução (RAM)",
    os: "VRP",
  },

  // ===== JUNIPER JUNOS OS COMMANDS =====
  {
    id: "juniper-1",
    vendor: "Juniper",
    category: "Interface Status",
    command: "show interfaces terse",
    description: "Exibe o status de Link (físico) e Protocol (lógico) de todas as interfaces",
    os: "Junos OS",
  },
  {
    id: "juniper-2",
    vendor: "Juniper",
    category: "Optical Signals",
    command: "show interfaces diagnostics optics [nome-da-interface]",
    description: "Exibe os níveis de potência óptica (TX/RX) e diagnósticos do transceptor",
    os: "Junos OS",
  },
  {
    id: "juniper-3",
    vendor: "Juniper",
    category: "Configuration",
    command: "configure",
    description: "Entra no modo de edição da configuração",
    os: "Junos OS",
    mode: "Operational Mode",
  },
  {
    id: "juniper-4",
    vendor: "Juniper",
    category: "Configuration",
    command: "commit",
    description: "Salva e aplica as alterações na configuração ativa",
    os: "Junos OS",
    mode: "Edit Mode",
  },
  {
    id: "juniper-5",
    vendor: "Juniper",
    category: "Shutdown",
    command: "deactivate",
    description: "Desativa a interface (shutdown administrativo)",
    os: "Junos OS",
    mode: "Edit Mode",
  },
  {
    id: "juniper-6",
    vendor: "Juniper",
    category: "Shutdown",
    command: "activate",
    description: "Ativa a interface",
    os: "Junos OS",
    mode: "Edit Mode",
  },
  {
    id: "juniper-7",
    vendor: "Juniper",
    category: "Subscribers",
    command: "show subscribers",
    description: "Lista todos os clientes PPPoE conectados",
    os: "Junos OS",
  },
  {
    id: "juniper-8",
    vendor: "Juniper",
    category: "Subscribers",
    command: "show subscribers user-name [usuário] extensive",
    description: "Exibe todos os detalhes da sessão do assinante",
    os: "Junos OS",
  },
  {
    id: "juniper-9",
    vendor: "Juniper",
    category: "Subscribers",
    command: "clear network-access aaa subscriber username [usuário]",
    description: "Desconecta o assinante PPPoE",
    os: "Junos OS",
  },
  {
    id: "juniper-10",
    vendor: "Juniper",
    category: "Subscribers",
    command: "test aaa ppp user [usuário] password [senha]",
    description: "Testa a autenticação do usuário no servidor RADIUS",
    os: "Junos OS",
  },
  {
    id: "juniper-11",
    vendor: "Juniper",
    category: "Diagnostics",
    command: "monitor interface [interface-lógica]",
    description: "Exibe o tráfego em tempo real (bps) de uma interface",
    os: "Junos OS",
  },
  {
    id: "juniper-12",
    vendor: "Juniper",
    category: "Diagnostics",
    command: "monitor traffic interface [interface] detail",
    description: "Captura e exibe pacotes em tempo real",
    os: "Junos OS",
  },

  // ===== DATACOM COMMANDS =====
  {
    id: "datacom-1",
    vendor: "Datacom",
    category: "Interface Status",
    command: "show interface status",
    description: "Exibe o status resumido de todas as interfaces",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-2",
    vendor: "Datacom",
    category: "Optical Signals",
    command: "show interface transceiver",
    description: "Exibe os níveis de potência óptica de todos os transceptores",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-3",
    vendor: "Datacom",
    category: "Optical Signals",
    command: "show interface transceiver detail",
    description: "Exibe detalhes completos dos transceptores (temperatura, voltagem)",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-4",
    vendor: "Datacom",
    category: "Configuration",
    command: "show running-config",
    description: "Exibe a configuração atual do dispositivo",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-5",
    vendor: "Datacom",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "DmOS / DmSwitch",
    mode: "Interface Config",
  },
  {
    id: "datacom-6",
    vendor: "Datacom",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a interface",
    os: "DmOS / DmSwitch",
    mode: "Interface Config",
  },

  // ===== ZTE COMMANDS =====
  {
    id: "zte-1",
    vendor: "ZTE",
    category: "Interface Status",
    command: "show interface [tipo/número]",
    description: "Exibe o status da interface especificada",
    os: "ROS / ZXROS",
  },
  {
    id: "zte-2",
    vendor: "ZTE",
    category: "Optical Signals",
    command: "show interface optical-module-info [tipo/número]",
    description: "Exibe os níveis de potência óptica (TX/RX) do transceptor",
    os: "OLT (C300/C600)",
  },
  {
    id: "zte-3",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon remote-onu interface [onu-id] optical-info",
    description: "Exibe os níveis de sinal (TX/RX) da ONU específica",
    os: "OLT",
  },
  {
    id: "zte-4",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon onu state [slot/porta] [onu-id]",
    description: "Verifica se a ONU está online e em estado normal",
    os: "OLT",
  },
  {
    id: "zte-5",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon onu all",
    description: "Lista todas as ONUs descobertas na OLT",
    os: "OLT",
  },
  {
    id: "zte-6",
    vendor: "ZTE",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "ROS / ZXROS",
    mode: "Interface Config",
  },
  {
    id: "zte-7",
    vendor: "ZTE",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a interface",
    os: "ROS / ZXROS",
    mode: "Interface Config",
  },

  // ===== NOKIA SROS COMMANDS =====
  {
    id: "nokia-1",
    vendor: "Nokia",
    category: "Interface Status",
    command: "show port",
    description: "Exibe o status resumido de todas as portas",
    os: "SROS",
  },
  {
    id: "nokia-2",
    vendor: "Nokia",
    category: "Optical Signals",
    command: "show port [porta] optical-diagnostic",
    description: "Exibe informações de diagnóstico óptico (TX/RX) da porta",
    os: "SROS",
  },
  {
    id: "nokia-3",
    vendor: "Nokia",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a porta em estado administrativo down",
    os: "SROS",
    mode: "Port Config",
  },
  {
    id: "nokia-4",
    vendor: "Nokia",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a porta",
    os: "SROS",
    mode: "Port Config",
  },
];

export const vendors = ["Cisco", "Huawei", "Juniper", "Datacom", "ZTE", "Nokia"];
export const categories = [
  "Interface Status",
  "Optical Signals",
  "Configuration",
  "Shutdown",
  "Diagnostics",
  "Logs",
  "Subscribers",
  "GPON",
];
