export interface Command {
  id: string;
  category: string;
  command: string;
  description: string;
  vendor: string;
  os?: string;
  mode?: string;
}

export const commandsData: Command[] = [
  // ===== CISCO COMMANDS =====
  {
    id: "cisco-1",
    vendor: "Cisco",
    category: "Interface Status",
    command: "show interface status",
    description: "Exibe o status resumido de todas as interfaces (Link e Protocol)",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-2",
    vendor: "Cisco",
    category: "Optical Signals",
    command: "show interface [tipo/número] transceiver detail",
    description: "Exibe os níveis de potência óptica (TX/RX) do transceptor SFP",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-3",
    vendor: "Cisco",
    category: "Configuration",
    command: "configure terminal",
    description: "Entra no modo de configuração global",
    os: "IOS / IOS-XE",
    mode: "User Mode",
  },
  {
    id: "cisco-4",
    vendor: "Cisco",
    category: "Configuration",
    command: "write memory",
    description: "Salva a configuração na memória não volátil",
    os: "IOS / IOS-XE",
    mode: "Privileged Mode",
  },
  {
    id: "cisco-5",
    vendor: "Cisco",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "IOS / IOS-XE",
    mode: "Interface Config",
  },
  {
    id: "cisco-6",
    vendor: "Cisco",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a interface",
    os: "IOS / IOS-XE",
    mode: "Interface Config",
  },
  {
    id: "cisco-7",
    vendor: "Cisco",
    category: "Diagnostics",
    command: "ping [IP]",
    description: "Testa conectividade com um endereço IP",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-8",
    vendor: "Cisco",
    category: "Diagnostics",
    command: "traceroute [IP]",
    description: "Exibe o caminho percorrido pelos pacotes até o destino",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-9",
    vendor: "Cisco",
    category: "Logs",
    command: "show logging",
    description: "Exibe os logs do sistema",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-10",
    vendor: "Cisco",
    category: "Configuration",
    command: "show running-config",
    description: "Exibe a configuração atual em execução",
    os: "IOS / IOS-XE",
  },
  // Novos comandos Cisco
  {
    id: "cisco-11",
    vendor: "Cisco",
    category: "VLAN Management",
    command: "show vlan brief",
    description: "Exibe todas as VLANs configuradas de forma resumida",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-12",
    vendor: "Cisco",
    category: "VLAN Management",
    command: "show vlan id [vlan-id]",
    description: "Exibe detalhes de uma VLAN específica",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-13",
    vendor: "Cisco",
    category: "Routing",
    command: "show ip route",
    description: "Exibe a tabela de roteamento completa",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-14",
    vendor: "Cisco",
    category: "Routing",
    command: "show ip ospf neighbor",
    description: "Exibe vizinhos OSPF e seu estado",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-15",
    vendor: "Cisco",
    category: "Routing",
    command: "show ip bgp summary",
    description: "Exibe resumo de sessões BGP",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-16",
    vendor: "Cisco",
    category: "Link Aggregation",
    command: "show etherchannel summary",
    description: "Exibe status de agregação de interfaces (EtherChannel)",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-17",
    vendor: "Cisco",
    category: "QoS",
    command: "show policy-map",
    description: "Exibe todas as políticas de QoS configuradas",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-18",
    vendor: "Cisco",
    category: "Security",
    command: "show access-lists",
    description: "Exibe todas as listas de controle de acesso (ACLs)",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-19",
    vendor: "Cisco",
    category: "System Information",
    command: "show version",
    description: "Exibe versão do IOS e informações do hardware",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-20",
    vendor: "Cisco",
    category: "System Information",
    command: "show processes cpu",
    description: "Exibe utilização de CPU por processo",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-21",
    vendor: "Cisco",
    category: "Monitoring",
    command: "show interface [tipo/número] counters",
    description: "Exibe contadores de pacotes e bytes da interface",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-22",
    vendor: "Cisco",
    category: "Monitoring",
    command: "show interface [tipo/número] errors",
    description: "Exibe erros (CRC, colisões, etc) da interface",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-23",
    vendor: "Cisco",
    category: "Advanced Diagnostics",
    command: "show tech-support",
    description: "Coleta informações completas do dispositivo para troubleshooting",
    os: "IOS / IOS-XE",
  },
  {
    id: "cisco-24",
    vendor: "Cisco",
    category: "Advanced Diagnostics",
    command: "debug ip packet",
    description: "Ativa debug de pacotes IP (use 'undebug all' para desativar)",
    os: "IOS / IOS-XE",
  },

  // ===== HUAWEI VRP COMMANDS =====
  {
    id: "huawei-1",
    vendor: "Huawei",
    category: "Interface Status",
    command: "display interface brief",
    description: "Exibe o status resumido de todas as interfaces (Link e Protocol)",
    os: "VRP",
  },
  {
    id: "huawei-2",
    vendor: "Huawei",
    category: "Optical Signals",
    command: "display interface [tipo/número] transceiver verbose",
    description: "Exibe os níveis de potência óptica (TX/RX) e temperatura do transceptor",
    os: "VRP",
  },
  {
    id: "huawei-3",
    vendor: "Huawei",
    category: "Configuration",
    command: "system-view",
    description: "Entra no modo de configuração global",
    os: "VRP",
    mode: "User View",
  },
  {
    id: "huawei-4",
    vendor: "Huawei",
    category: "Configuration",
    command: "save",
    description: "Salva a configuração na memória não volátil",
    os: "VRP",
    mode: "System View",
  },
  {
    id: "huawei-5",
    vendor: "Huawei",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "VRP",
    mode: "Interface View",
  },
  {
    id: "huawei-6",
    vendor: "Huawei",
    category: "Shutdown",
    command: "undo shutdown",
    description: "Ativa a interface",
    os: "VRP",
    mode: "Interface View",
  },
  {
    id: "huawei-7",
    vendor: "Huawei",
    category: "Diagnostics",
    command: "ping [IP]",
    description: "Testa conectividade com um endereço IP",
    os: "VRP",
  },
  {
    id: "huawei-8",
    vendor: "Huawei",
    category: "Diagnostics",
    command: "tracert [IP]",
    description: "Exibe o caminho percorrido pelos pacotes até o destino",
    os: "VRP",
  },
  {
    id: "huawei-9",
    vendor: "Huawei",
    category: "Logs",
    command: "display logbuffer",
    description: "Exibe os logs de eventos do sistema",
    os: "VRP",
  },
  {
    id: "huawei-10",
    vendor: "Huawei",
    category: "Configuration",
    command: "display current-configuration",
    description: "Exibe a configuração atual em execução (RAM)",
    os: "VRP",
  },
  // Novos comandos Huawei
  {
    id: "huawei-11",
    vendor: "Huawei",
    category: "VLAN Management",
    command: "display vlan all",
    description: "Exibe todas as VLANs configuradas",
    os: "VRP",
  },
  {
    id: "huawei-12",
    vendor: "Huawei",
    category: "VLAN Management",
    command: "display vlan [vlan-id]",
    description: "Exibe detalhes de uma VLAN específica",
    os: "VRP",
  },
  {
    id: "huawei-13",
    vendor: "Huawei",
    category: "Routing",
    command: "display ip routing-table",
    description: "Exibe a tabela de roteamento completa",
    os: "VRP",
  },
  {
    id: "huawei-14",
    vendor: "Huawei",
    category: "Routing",
    command: "display ospf neighbor",
    description: "Exibe vizinhos OSPF e seu estado",
    os: "VRP",
  },
  {
    id: "huawei-15",
    vendor: "Huawei",
    category: "Routing",
    command: "display bgp peer",
    description: "Exibe vizinhos BGP",
    os: "VRP",
  },
  {
    id: "huawei-16",
    vendor: "Huawei",
    category: "Link Aggregation",
    command: "display eth-trunk",
    description: "Exibe status de agregação de interfaces",
    os: "VRP",
  },
  {
    id: "huawei-17",
    vendor: "Huawei",
    category: "QoS",
    command: "display qos policy",
    description: "Exibe políticas de QoS configuradas",
    os: "VRP",
  },
  {
    id: "huawei-18",
    vendor: "Huawei",
    category: "Security",
    command: "display acl all",
    description: "Exibe todas as listas de controle de acesso (ACLs)",
    os: "VRP",
  },
  {
    id: "huawei-19",
    vendor: "Huawei",
    category: "System Information",
    command: "display version",
    description: "Exibe versão do VRP e informações do hardware",
    os: "VRP",
  },
  {
    id: "huawei-20",
    vendor: "Huawei",
    category: "System Information",
    command: "display cpu-usage",
    description: "Exibe utilização de CPU em tempo real",
    os: "VRP",
  },
  {
    id: "huawei-21",
    vendor: "Huawei",
    category: "Monitoring",
    command: "display interface [tipo/número] statistics",
    description: "Exibe estatísticas detalhadas da interface",
    os: "VRP",
  },
  {
    id: "huawei-22",
    vendor: "Huawei",
    category: "Advanced Diagnostics",
    command: "display logbuffer | include [palavra-chave]",
    description: "Busca palavra-chave nos logs do sistema",
    os: "VRP",
  },

  // ===== JUNIPER JUNOS OS COMMANDS =====
  {
    id: "juniper-1",
    vendor: "Juniper",
    category: "Interface Status",
    command: "show interfaces terse",
    description: "Exibe o status de Link (físico) e Protocol (lógico) de todas as interfaces",
    os: "Junos OS",
  },
  {
    id: "juniper-2",
    vendor: "Juniper",
    category: "Optical Signals",
    command: "show interfaces diagnostics optics [nome-da-interface]",
    description: "Exibe os níveis de potência óptica (TX/RX) e diagnósticos do transceptor",
    os: "Junos OS",
  },
  {
    id: "juniper-3",
    vendor: "Juniper",
    category: "Configuration",
    command: "configure",
    description: "Entra no modo de edição da configuração",
    os: "Junos OS",
    mode: "Operational Mode",
  },
  {
    id: "juniper-4",
    vendor: "Juniper",
    category: "Configuration",
    command: "commit",
    description: "Salva e aplica as alterações na configuração ativa",
    os: "Junos OS",
    mode: "Edit Mode",
  },
  {
    id: "juniper-5",
    vendor: "Juniper",
    category: "Shutdown",
    command: "deactivate",
    description: "Desativa a interface (shutdown administrativo)",
    os: "Junos OS",
    mode: "Edit Mode",
  },
  {
    id: "juniper-6",
    vendor: "Juniper",
    category: "Shutdown",
    command: "activate",
    description: "Ativa a interface",
    os: "Junos OS",
    mode: "Edit Mode",
  },
  {
    id: "juniper-7",
    vendor: "Juniper",
    category: "Subscribers",
    command: "show subscribers",
    description: "Lista todos os clientes PPPoE conectados",
    os: "Junos OS",
  },
  {
    id: "juniper-8",
    vendor: "Juniper",
    category: "Subscribers",
    command: "show subscribers user-name [usuário] extensive",
    description: "Exibe todos os detalhes da sessão do assinante",
    os: "Junos OS (BNG)",
  },
  {
    id: "juniper-9",
    vendor: "Juniper",
    category: "Diagnostics",
    command: "ping [IP]",
    description: "Testa conectividade com um endereço IP",
    os: "Junos OS",
  },
  {
    id: "juniper-10",
    vendor: "Juniper",
    category: "Logs",
    command: "show log [arquivo-log]",
    description: "Exibe conteúdo de arquivos de log do sistema",
    os: "Junos OS",
  },
  // Novos comandos Juniper
  {
    id: "juniper-11",
    vendor: "Juniper",
    category: "VLAN Management",
    command: "show vlans",
    description: "Exibe todas as VLANs configuradas",
    os: "Junos OS",
  },
  {
    id: "juniper-12",
    vendor: "Juniper",
    category: "Routing",
    command: "show route",
    description: "Exibe a tabela de roteamento completa",
    os: "Junos OS",
  },
  {
    id: "juniper-13",
    vendor: "Juniper",
    category: "Routing",
    command: "show ospf neighbor",
    description: "Exibe vizinhos OSPF e seu estado",
    os: "Junos OS",
  },
  {
    id: "juniper-14",
    vendor: "Juniper",
    category: "Routing",
    command: "show bgp summary",
    description: "Exibe resumo de sessões BGP",
    os: "Junos OS",
  },
  {
    id: "juniper-15",
    vendor: "Juniper",
    category: "Link Aggregation",
    command: "show interfaces ae[number]",
    description: "Exibe status de agregação de interfaces",
    os: "Junos OS",
  },
  {
    id: "juniper-16",
    vendor: "Juniper",
    category: "QoS",
    command: "show class-of-service",
    description: "Exibe configuração de QoS",
    os: "Junos OS",
  },
  {
    id: "juniper-17",
    vendor: "Juniper",
    category: "Security",
    command: "show firewall filter",
    description: "Exibe filtros de firewall configurados",
    os: "Junos OS",
  },
  {
    id: "juniper-18",
    vendor: "Juniper",
    category: "System Information",
    command: "show version",
    description: "Exibe versão do Junos e informações do hardware",
    os: "Junos OS",
  },
  {
    id: "juniper-19",
    vendor: "Juniper",
    category: "System Information",
    command: "show system processes",
    description: "Exibe processos do sistema e utilização de recursos",
    os: "Junos OS",
  },
  {
    id: "juniper-20",
    vendor: "Juniper",
    category: "Monitoring",
    command: "show interfaces [interface] statistics",
    description: "Exibe estatísticas detalhadas da interface",
    os: "Junos OS",
  },
  {
    id: "juniper-21",
    vendor: "Juniper",
    category: "Subscribers",
    command: "show subscribers count",
    description: "Exibe quantidade total de assinantes PPPoE conectados",
    os: "Junos OS (BNG)",
  },
  {
    id: "juniper-22",
    vendor: "Juniper",
    category: "Advanced Diagnostics",
    command: "monitor interface [interface]",
    description: "Monitora tráfego em tempo real da interface",
    os: "Junos OS",
  },

  // ===== DATACOM COMMANDS =====
  {
    id: "datacom-1",
    vendor: "Datacom",
    category: "Interface Status",
    command: "show interface [tipo/número]",
    description: "Exibe o status da interface especificada",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-2",
    vendor: "Datacom",
    category: "Optical Signals",
    command: "show interface [tipo/número] transceiver",
    description: "Exibe os níveis de potência óptica (TX/RX) do transceptor",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-3",
    vendor: "Datacom",
    category: "Configuration",
    command: "configure terminal",
    description: "Entra no modo de configuração global",
    os: "DmOS / DmSwitch",
    mode: "User Mode",
  },
  {
    id: "datacom-4",
    vendor: "Datacom",
    category: "Configuration",
    command: "write memory",
    description: "Salva a configuração na memória não volátil",
    os: "DmOS / DmSwitch",
    mode: "Config Mode",
  },
  {
    id: "datacom-5",
    vendor: "Datacom",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "DmOS / DmSwitch",
    mode: "Interface Config",
  },
  {
    id: "datacom-6",
    vendor: "Datacom",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a interface",
    os: "DmOS / DmSwitch",
    mode: "Interface Config",
  },
  // Novos comandos Datacom
  {
    id: "datacom-7",
    vendor: "Datacom",
    category: "VLAN Management",
    command: "show vlan",
    description: "Exibe todas as VLANs configuradas",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-8",
    vendor: "Datacom",
    category: "Routing",
    command: "show ip route",
    description: "Exibe a tabela de roteamento",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-9",
    vendor: "Datacom",
    category: "System Information",
    command: "show version",
    description: "Exibe versão do DmOS e informações do hardware",
    os: "DmOS / DmSwitch",
  },
  {
    id: "datacom-10",
    vendor: "Datacom",
    category: "Diagnostics",
    command: "ping [IP]",
    description: "Testa conectividade com um endereço IP",
    os: "DmOS / DmSwitch",
  },

  // ===== ZTE COMMANDS =====
  {
    id: "zte-1",
    vendor: "ZTE",
    category: "Interface Status",
    command: "show interface [tipo/número]",
    description: "Exibe o status da interface especificada",
    os: "ROS / ZXROS",
  },
  {
    id: "zte-2",
    vendor: "ZTE",
    category: "Optical Signals",
    command: "show interface optical-module-info [tipo/número]",
    description: "Exibe os níveis de potência óptica (TX/RX) do transceptor",
    os: "OLT (C300/C600)",
  },
  {
    id: "zte-3",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon remote-onu interface [onu-id] optical-info",
    description: "Exibe os níveis de sinal (TX/RX) da ONU específica",
    os: "OLT",
  },
  {
    id: "zte-4",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon onu state [slot/porta] [onu-id]",
    description: "Verifica se a ONU está online e em estado normal",
    os: "OLT",
  },
  {
    id: "zte-5",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon onu all",
    description: "Lista todas as ONUs descobertas na OLT",
    os: "OLT",
  },
  {
    id: "zte-6",
    vendor: "ZTE",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a interface em estado administrativo down",
    os: "ROS / ZXROS",
    mode: "Interface Config",
  },
  {
    id: "zte-7",
    vendor: "ZTE",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a interface",
    os: "ROS / ZXROS",
    mode: "Interface Config",
  },
  // Novos comandos ZTE
  {
    id: "zte-8",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon onu performance [slot/porta] [onu-id]",
    description: "Exibe performance e estatísticas da ONU",
    os: "OLT",
  },
  {
    id: "zte-9",
    vendor: "ZTE",
    category: "GPON",
    command: "show gpon onu traffic [slot/porta] [onu-id]",
    description: "Exibe tráfego (entrada/saída) da ONU",
    os: "OLT",
  },
  {
    id: "zte-10",
    vendor: "ZTE",
    category: "System Information",
    command: "show version",
    description: "Exibe versão do ROS/ZXROS e informações do hardware",
    os: "ROS / ZXROS",
  },
  {
    id: "zte-11",
    vendor: "ZTE",
    category: "Diagnostics",
    command: "ping [IP]",
    description: "Testa conectividade com um endereço IP",
    os: "ROS / ZXROS",
  },

  // ===== NOKIA SROS COMMANDS =====
  {
    id: "nokia-1",
    vendor: "Nokia",
    category: "Interface Status",
    command: "show port",
    description: "Exibe o status resumido de todas as portas",
    os: "SROS",
  },
  {
    id: "nokia-2",
    vendor: "Nokia",
    category: "Optical Signals",
    command: "show port [porta] optical-diagnostic",
    description: "Exibe informações de diagnóstico óptico (TX/RX) da porta",
    os: "SROS",
  },
  {
    id: "nokia-3",
    vendor: "Nokia",
    category: "Shutdown",
    command: "shutdown",
    description: "Coloca a porta em estado administrativo down",
    os: "SROS",
    mode: "Port Config",
  },
  {
    id: "nokia-4",
    vendor: "Nokia",
    category: "Shutdown",
    command: "no shutdown",
    description: "Ativa a porta",
    os: "SROS",
    mode: "Port Config",
  },
  // Novos comandos Nokia
  {
    id: "nokia-5",
    vendor: "Nokia",
    category: "VLAN Management",
    command: "show service id [service-id]",
    description: "Exibe detalhes de um serviço específico",
    os: "SROS",
  },
  {
    id: "nokia-6",
    vendor: "Nokia",
    category: "Routing",
    command: "show route-table",
    description: "Exibe a tabela de roteamento",
    os: "SROS",
  },
  {
    id: "nokia-7",
    vendor: "Nokia",
    category: "Routing",
    command: "show router ospf neighbor",
    description: "Exibe vizinhos OSPF",
    os: "SROS",
  },
  {
    id: "nokia-8",
    vendor: "Nokia",
    category: "Security",
    command: "show filter",
    description: "Exibe filtros de firewall configurados",
    os: "SROS",
  },
  {
    id: "nokia-9",
    vendor: "Nokia",
    category: "System Information",
    command: "show system information",
    description: "Exibe informações gerais do sistema",
    os: "SROS",
  },
  {
    id: "nokia-10",
    vendor: "Nokia",
    category: "Monitoring",
    command: "show port [porta] statistics",
    description: "Exibe estatísticas detalhadas da porta",
    os: "SROS",
  },
];

export const vendors = ["Cisco", "Huawei", "Juniper", "Datacom", "ZTE", "Nokia"];
export const categories = [
  "Interface Status",
  "Optical Signals",
  "Configuration",
  "Shutdown",
  "Diagnostics",
  "Logs",
  "Subscribers",
  "GPON",
  "VLAN Management",
  "Routing",
  "Link Aggregation",
  "QoS",
  "Security",
  "System Information",
  "Monitoring",
  "Advanced Diagnostics",
];
